import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MenuList from '../components/MenuList';
import { useQuery } from 'react-query';
import { convertKeys } from '../utils/lib';
import axios from 'axios';
const instance = axios.create({
  crossDomain: true,
  headers: {'authorizationToken': 'cloud2022'}
});
const API_URL = "https://fh34mm97a6.execute-api.us-east-1.amazonaws.com/dev";

// const API_URL = 'http://localhost:3000/api/menu';
export default function Home() {
  // Fetch Data
  const { isLoading, error, data } = useQuery('repoData', () =>
    // fetch('http://localhost:3000/api/menu').then((res) =>
    //   convertKeys(res.json())
    // )
    instance.get(API_URL).then((res) => {
      return convertKeys(res.data);
    })
  );

  if (isLoading) return 'Loading...';
  if (error) return 'An error has occurred: ' + error.message;
  return (
    <div className={styles.container}>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Menu</h1>
        <MenuList menuItems={data} />
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
}
