import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { convertKeys } from '../utils/lib';
import MenuItemsGrid from '../components/MenuItemsGrid';
import menuData from '../data.json';
import MenuTable from '../components/MenuTable';

export default function Home({ menuItems }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Static Menu Table</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Static Menu Table</h1>
        <MenuTable menuItems={menuItems} />
        {/* <MenuItemsGrid menuItems={menuItems} /> */}
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  //   const res = await fetch('http://localhost:3000/api/menu');
  //   const data = await res.json();
  //   const menuItems = convertKeys(data);
  const menuItems = convertKeys(menuData);
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      menuItems,
    },
  };
}
