import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { convertKeys } from './_lib';
import MenuList from './components/MenuList';
import MenuItemsGrid from './components/MenuItemsGrid';

export default function Home({ menuItems }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Menu</h1>

        <MenuItemsGrid menuItems={menuItems} />
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('http://localhost:3000/api/menu');
  const data = await res.json();
  const menuItems = convertKeys(data);
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      menuItems,
    },
  };
}
